version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8761/eureka"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
    volumes:
      - ./product-service/src:/app/src
      - ./product-service/target/classes:/app/target/classes
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/products
    depends_on:
      - discovery-server
      - mongo
    links:
      - discovery-server

volumes:
  mongo_data:
