version: '3.8'

services:
  # postgres:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: orders
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - backend

  # mongodb:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - backend

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"   # 👈 very important: expose 8761
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - discovery-server
  #   networks:
  #     - backend
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker

  # product-service:
  #   build: ./product-service
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongodb
  #     - discovery-server
  #   networks:
  #     - backend
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker

  # Add order-service, cart-service etc. similarly...

networks:
  backend:
